### ISSUE TITLE
G3l ?

### ISSUE THREAD

**Issue by cagataycali** [mahammad/gg-Tool#1]
Did you see g3l?
https://www.npmjs.com/package/g3l

**Comment by mahammad** [comment]
npm'i gördüm yüklüyesim  gelmedi. Bana böyle script yeterli geldi dedim burda dursun sen olayı geniş düşünmüşsün güzel :+1: .

**Comment by cagataycali** [comment]
Ubuntu için : 

```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

```
npm i -g g3l 
```

👍

**Comment by mahammad** [comment]
Teşekkürler :grinning:
